spring:
  datasource:
    username: root
    password: pass
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/play_devblog
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialectddialect: org.hibernate.dialect.MySQLInnoDBDialect
